services:
  evently.database:
    container_name: evently.database
    image: postgres:18.1-alpine3.23
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 10s
      interval: 10s
      retries: 3
      timeout: 10s

  evently.cache:
    container_name: evently.cache
    image: redis:8.4.0-alpine3.22
    restart: unless-stopped
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      start_period: 10s
      interval: 10s
      retries: 3
      timeout: 10s

  evently.identity:
    container_name: evently.identity
    image: quay.io/keycloak/keycloak:26.5.2
    restart: unless-stopped
    command: start-dev --import-realm
    ports:
      - 18000:8080
      - 18001:9000
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./files:/opt/keycloak/data/import

  evently.queue:
    container_name: evently.queue
    image: rabbitmq:4.2.4-management-alpine
    restart: unless-stopped
    hostname: evently-queue
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      start_period: 10s
      interval: 10s
      retries: 3
      timeout: 10s

  evently.pgAdmin:
    container_name: evently.pgAdmin
    image: dpage/pgadmin4:9.12.0
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-data:/certs/server.cert
      - pgadmin-data:/certs/server.key
      - pgadmin-data:/pgadmin4/servers.json
    depends_on:
      evently.database:
        condition: service_healthy
        restart: true

  evently.redis-insight:
    container_name: evently.redis-insight
    image: redis/redisinsight:3.0.2
    restart: unless-stopped
    ports:
      - 8081:5540
    volumes:
      - redis-insight-data:/data
    depends_on:
      evently.cache:
        condition: service_healthy
        restart: true

  evently.seq:
    container_name: evently.seq
    image: datalust/seq:2025.2
    restart: unless-stopped
    ports:
      - 8082:80
      - 5341:5341
    environment:
      ACCEPT_EULA: "Y"
      SEQ_PASSWORD: ${SEQ_PASSWORD}
    volumes:
      - seq-data:/data

  evently.jaeger:
    container_name: evently.jaeger
    image: jaegertracing/jaeger:2.15.1
    restart: unless-stopped
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318

volumes:
  postgres-data:
  keycloak-data:
  rabbitmq-data:
  pgadmin-data:
    external: true
  redis-insight-data:
  seq-data:
